SELECT
/* C_SYSDATE.OUTGRP1 */
  NULL "MERGE_COL_ALIAS",
  SYSDATE/* ATTRIBUTE C_SYSDATE.OUTGRP1.C_SYSDATE */ "C_SYSDATE",
  "C"."SRC_CASE_ID" "SRC_CASE_ID",
  "C"."CASE_COND_FLG" "CASE_COND_FLG",
  "C"."CASE_COND_FLG_DESCR" "CASE_COND_FLG_DESCR",
  "C"."CASE_STATUS_CD" "CASE_STATUS_CD",
  "C"."CASE_STATUS_CD_DESCR" "CASE_STATUS_CD_DESCR",
  "C"."CASE_TYPE_CD" "CASE_TYPE_CD",
  "C"."CASE_TYPE_CD_DESCR" "CASE_TYPE_CD_DESCR",
  "C"."COMMENT_LONG" "COMMENT_LONG",
  "C"."CONTACT_INSTR" "CONTACT_INSTR",
  "C"."CONTACT_METH_FLG" "CONTACT_METH_FLG",
  "C"."CONTACT_METH_FLG_DESCR" "CONTACT_METH_FLG_DESCR",
  "C"."USER_ID" "USER_ID",
  "C"."USER_ID_CIS_USER_KEY" "USER_ID_CIS_USER_KEY",
  "C"."PER_ID" "PER_ID",
  "C"."ACCT_ID" "ACCT_ID",
  "C"."PREM_ID" "PREM_ID",
  "C"."CONTACT_PER_ID" "CONTACT_PER_ID",
  "C"."START_DT" "START_DT",
  "C"."START_DT_CAL_KEY" "START_DT_CAL_KEY",
  "D"."STATUS_DT" "STATUS_DT_0",
  "C"."STATUS_DT_CAL_KEY" "STATUS_DT_CAL_KEY",
  "C"."PERSON_KEY" "PERSON_KEY",
  "C"."ACCOUNT_KEY" "ACCOUNT_KEY",
  "C"."PREMISE_KEY" "PREMISE_KEY",
  "C"."CONTACT_PERSON_KEY" "CONTACT_PERSON_KEY",
  "C"."DELETED_DTTM" "DELETED_DTTM",
  "C"."DELETED_FLG" "DELETED_FLG"
FROM
   ( SELECT
/* ST2_CI_CASE.INOUTGRP1, EXPRESSION.OUTGRP1 */
  NVL(TRIM("ST2_CI_CASE"."CASE_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.CASE_ID: EXPRESSION */ "SRC_CASE_ID",
  "ST2_CI_CASE"."CASE_COND_FLG" "CASE_COND_FLG",
  NVL("ST2_CI_LOOKUP_VAL_L"."DESCR", 'N/A') "CASE_COND_FLG_DESCR",
  "ST2_CI_CASE"."CASE_STATUS_CD" "CASE_STATUS_CD",
  NVL("ST2_CI_CASE_STATUS_L"."STATUS_LBL", 'N/A') "CASE_STATUS_CD_DESCR",
  NVL(TRIM("ST2_CI_CASE"."CASE_TYPE_CD"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.CASE_TYPE_CD: EXPRESSION */ "CASE_TYPE_CD",
  NVL((SELECT
  "ST2_CI_CASE_TYPE_L_S"."DESCR" "DESCR"
FROM
  "ST2_CI_CASE_TYPE_L"  "ST2_CI_CASE_TYPE_L_S"
  WHERE 
  ( "ST2_CI_CASE_TYPE_L_S"."CASE_TYPE_CD" = "ST2_CI_CASE"."CASE_TYPE_CD" ) /* OPERATOR ST2_CI_CASE_TYPE_L: LOOKUP CONDITION */ AND
  ( "ST2_CI_CASE_TYPE_L_S"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT_1.OUTGRP1.FIELD_NAME */ ) /* OPERATOR ST2_CI_CASE_TYPE_L: ROW MATCH */ AND
  ( rownum = 1 ) ), 'N/A') "CASE_TYPE_CD_DESCR",
  NVL(TRIM("ST2_CI_CASE"."COMMENT_LONG"),'N/A')/* ATTRIBUTE EXPRESSION_3.OUTGRP1.COMMENT_LONG: EXPRESSION */ "COMMENT_LONG",
  NVL(TRIM((TRIM( "ST2_CI_CASE"."CONTACT_INSTR" )/* ATTRIBUTE TRIM.OUTGRP1.CONTACT_INSTR: EXPRESSION */)),'N/A')/* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_INSTR: EXPRESSION */ "CONTACT_INSTR",
  NVL(TRIM("ST2_CI_CASE"."CONTACT_METH_FLG"),'N/A')/* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_METH_FLG: EXPRESSION */ "CONTACT_METH_FLG",
  NVL("ST2_CI_LOOKUP_VAL_L_1"."DESCR", 'N/A') "CONTACT_METH_FLG_DESCR",
  NVL(TRIM("ST2_CI_CASE"."USER_ID"),1)/* ATTRIBUTE EXPRESSION_3.OUTGRP1.USER_ID: EXPRESSION */ "USER_ID",
  NVL("D_CIS_USER"."CIS_USER_KEY", 1) "USER_ID_CIS_USER_KEY",
  NVL(TRIM("ST2_CI_CASE"."PER_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.PER_ID: EXPRESSION */ "PER_ID",
  NVL(TRIM("ST2_CI_CASE"."ACCT_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.ACCT_ID: EXPRESSION */ "ACCT_ID",
  NVL(TRIM("ST2_CI_CASE"."PREM_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.PREM_ID: EXPRESSION */ "PREM_ID",
  NVL(TRIM("ST2_CI_CASE"."CONTACT_PER_ID"),1)/* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_PER_ID: EXPRESSION */ "CONTACT_PER_ID",
  TRUNC("ST2_CI_CASE_LOG"."LOG_DTTM")/* ATTRIBUTE TRUNC.OUTGRP1.LOG_DTTM: EXPRESSION */ "START_DT",
  "D_DATE_1_1"."DATE_KEY" "START_DT_CAL_KEY",
  "D_DATE_1"."DATE_KEY" "STATUS_DT_CAL_KEY",
  NVL("D_PERSON"."PERSON_KEY", 1) "PERSON_KEY",
  NVL("D_ACCOUNT"."ACCOUNT_KEY", 1) "ACCOUNT_KEY",
  NVL("D_PREMISE"."PREMISE_KEY", 1) "PREMISE_KEY",
  NVL("D_PERSON_1"."PERSON_KEY", 1) "CONTACT_PERSON_KEY",
  CASE 
  WHEN "ST2_CI_CASE"."CASE_ID" IS NULL THEN SYSDATE 
  ELSE NULL 
END/* ATTRIBUTE EXPRESSION.OUTGRP1.DELETED_DTTM: EXPRESSION */ "DELETED_DTTM",
  CASE 
  WHEN "ST2_CI_CASE"."CASE_ID" IS NULL THEN 1 
  ELSE NULL 
END/* ATTRIBUTE EXPRESSION.OUTGRP1.DELETED_FLG: EXPRESSION */ "DELETED_FLG"
FROM
    "ST2_CI_LOOKUP_VAL_L"  "ST2_CI_LOOKUP_VAL_L"   
 RIGHT OUTER JOIN   "ST2_CI_CASE"  "ST2_CI_CASE" ON ( (( "ST2_CI_LOOKUP_VAL_L"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_LOOKUP_VAL_L"."FIELD_NAME" = 'CASE_COND_FLG'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_LOOKUP_VAL_L"."FIELD_VALUE" = "ST2_CI_CASE"."CASE_COND_FLG" )) )
 LEFT OUTER JOIN   "ST2_CI_CASE_STATUS_L"  "ST2_CI_CASE_STATUS_L" ON ( (( "ST2_CI_CASE_STATUS_L"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_CASE_STATUS_L"."CASE_TYPE_CD" = "ST2_CI_CASE"."CASE_TYPE_CD" )) AND (( "ST2_CI_CASE_STATUS_L"."CASE_STATUS_CD" = "ST2_CI_CASE"."CASE_STATUS_CD" )) )
 LEFT OUTER JOIN   "ST2_CI_LOOKUP_VAL_L"  "ST2_CI_LOOKUP_VAL_L_1" ON ( (( "ST2_CI_LOOKUP_VAL_L_1"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_LOOKUP_VAL_L_1"."FIELD_VALUE" = "ST2_CI_CASE"."CONTACT_METH_FLG" )) AND (( "ST2_CI_LOOKUP_VAL_L_1"."FIELD_NAME" = 'CONTACT_METH_FLG'/* ATTRIBUTE CONSTANT_1.OUTGRP1.FIELD_NAME */ )) )
 LEFT OUTER JOIN   "D_CIS_USER"  "D_CIS_USER" ON ( ( "D_CIS_USER"."SRC_USER_ID" = "ST2_CI_CASE"."USER_ID" ) )
 LEFT OUTER JOIN   "ST2_CI_CASE_LOG"  "ST2_CI_CASE_LOG" ON ( (( "ST2_CI_CASE_LOG"."CASE_ID" = "ST2_CI_CASE"."CASE_ID" )) AND (( "ST2_CI_CASE_LOG"."CASE_LOG_TYPE_FLG" = 'CASC'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) )
 LEFT OUTER JOIN   "D_DATE"  "D_DATE_1_1" ON ( ( "D_DATE_1_1"."SRC_DATE" = (TRUNC("ST2_CI_CASE_LOG"."LOG_DTTM")/* ATTRIBUTE TRUNC.OUTGRP1.LOG_DTTM: EXPRESSION */) ) )
 LEFT OUTER JOIN   "ST2_CI_CASE_LOG"  "ST2_CI_CASE_LOG_2" ON ( (( "ST2_CI_CASE_LOG_2"."CASE_LOG_TYPE_FLG" = 'CASC'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_CASE_LOG_2"."CASE_ID" = "ST2_CI_CASE"."CASE_ID" )) )
 LEFT OUTER JOIN   "D_DATE"  "D_DATE_1" ON ( ( "D_DATE_1"."SRC_DATE" = (TRUNC("ST2_CI_CASE_LOG_2"."LOG_DTTM")/* ATTRIBUTE TRUNC_2.OUTGRP1.LOG_DTTM: EXPRESSION */) ) )
 LEFT OUTER JOIN   "D_PERSON"  "D_PERSON" ON ( ( "D_PERSON"."SRC_PER_ID" = "ST2_CI_CASE"."PER_ID" ) )
 LEFT OUTER JOIN   "D_ACCOUNT"  "D_ACCOUNT" ON ( ( "D_ACCOUNT"."SRC_ACCT_ID" = "ST2_CI_CASE"."ACCT_ID" ) )
 LEFT OUTER JOIN   "D_PREMISE"  "D_PREMISE" ON ( ( "D_PREMISE"."SRC_PREM_ID" = "ST2_CI_CASE"."PREM_ID" ) )
 LEFT OUTER JOIN   "D_PERSON"  "D_PERSON_1" ON ( ( "D_PERSON_1"."SRC_PER_ID" = "ST2_CI_CASE"."CONTACT_PER_ID" ) ) ) "C"   
 LEFT OUTER JOIN  ( SELECT
/* JOINER.OUTGRP1 */
  "ST2_CI_CASE"."CASE_ID" "SRC_CASE_ID",
  CASE 
   WHEN  "INGRP2"."CASE_LOG_TYPE_FLG" is null and "INGRP3"."CASE_LOG_TYPE_FLG"='CASC' 
   THEN (TRUNC("INGRP3"."LOG_DTTM")/* ATTRIBUTE TRUNC_2_1.OUTGRP1.LOG_DTTM_0: EXPRESSION */)
   WHEN  "INGRP2"."CASE_LOG_TYPE_FLG" ='STAT' and "INGRP3"."CASE_LOG_TYPE_FLG"='CASC' 
    THEN (TRUNC("INGRP2"."LOG_DTTM")/* ATTRIBUTE TRUNC_2_1.OUTGRP1.LOG_DTTM: EXPRESSION */)
    ELSE  NULL
 END/* ATTRIBUTE EXPRESSION_1.OUTGRP1.STATUS_DT: EXPRESSION */ "STATUS_DT"
FROM
    "ST2_CI_CASE"  "ST2_CI_CASE"   
 LEFT OUTER JOIN  ( SELECT
/* ST2_CI_CASE_LOG_V.INOUTGRP1 */
  "ST2_CI_CASE_LOG_V"."CASE_ID" "CASE_ID",
  "ST2_CI_CASE_LOG_V"."LOG_DTTM" "LOG_DTTM",
  "ST2_CI_CASE_LOG_V"."CASE_LOG_TYPE_FLG" "CASE_LOG_TYPE_FLG"
FROM
  "ST2_CI_CASE_LOG_V"  "ST2_CI_CASE_LOG_V" ) "INGRP2" ON ( ( "ST2_CI_CASE"."CASE_ID" = "INGRP2"."CASE_ID" ) )
 LEFT OUTER JOIN  ( SELECT
/* ST2_CI_CASE_LOG_V1.INOUTGRP1 */
  "ST2_CI_CASE_LOG_V1"."CASE_ID" "CASE_ID",
  "ST2_CI_CASE_LOG_V1"."LOG_DTTM" "LOG_DTTM",
  "ST2_CI_CASE_LOG_V1"."CASE_LOG_TYPE_FLG" "CASE_LOG_TYPE_FLG"
FROM
  "ST2_CI_CASE_LOG_V1"  "ST2_CI_CASE_LOG_V1" ) "INGRP3" ON ( ( "ST2_CI_CASE"."CASE_ID" = "INGRP3"."CASE_ID" ) ) ) "D" ON ( ( "C"."SRC_CASE_ID" = "D"."SRC_CASE_ID" ) )
  )
    "MERGE_SUBQUERY"
ON (
  "D_CASE_3"."SRC_CASE_ID" = "MERGE_SUBQUERY"."SRC_CASE_ID"
   )




 SELECT
/* JOINER.OUTGRP1 */
  "ST2_CI_CASE"."CASE_ID" "SRC_CASE_ID",
  CASE 
   WHEN  "INGRP2"."CASE_LOG_TYPE_FLG" is null and "INGRP3"."CASE_LOG_TYPE_FLG"='CASC' 
   THEN (TRUNC("INGRP3"."LOG_DTTM")/* ATTRIBUTE TRUNC_2_1.OUTGRP1.LOG_DTTM_0: EXPRESSION */)
   WHEN  "INGRP2"."CASE_LOG_TYPE_FLG" ='STAT' and "INGRP3"."CASE_LOG_TYPE_FLG"='CASC' 
    THEN (TRUNC("INGRP2"."LOG_DTTM")/* ATTRIBUTE TRUNC_2_1.OUTGRP1.LOG_DTTM: EXPRESSION */)
    ELSE  NULL
  
 END/* ATTRIBUTE EXPRESSION_1.OUTGRP1.STATUS_DT: EXPRESSION */ "STATUS_DT"
FROM
    "ST2_CI_CASE"  "ST2_CI_CASE"   
 LEFT OUTER JOIN  ( SELECT
/* ST2_CI_CASE_LOG_V.INOUTGRP1 */
  "ST2_CI_CASE_LOG_V"."CASE_ID" "CASE_ID",
  "ST2_CI_CASE_LOG_V"."LOG_DTTM" "LOG_DTTM",
  "ST2_CI_CASE_LOG_V"."CASE_LOG_TYPE_FLG" "CASE_LOG_TYPE_FLG"
FROM
  "ST2_CI_CASE_LOG_V"  "ST2_CI_CASE_LOG_V" ) "INGRP2" ON ( ( "ST2_CI_CASE"."CASE_ID" = "INGRP2"."CASE_ID" ) )
 LEFT OUTER JOIN  ( SELECT
/* ST2_CI_CASE_LOG_V1.INOUTGRP1 */
  "ST2_CI_CASE_LOG_V1"."CASE_ID" "CASE_ID",
  "ST2_CI_CASE_LOG_V1"."LOG_DTTM" "LOG_DTTM",
  "ST2_CI_CASE_LOG_V1"."CASE_LOG_TYPE_FLG" "CASE_LOG_TYPE_FLG"
FROM
  "ST2_CI_CASE_LOG_V1"  "ST2_CI_CASE_LOG_V1" ) "INGRP3" ON ( ( "ST2_CI_CASE"."CASE_ID" = "INGRP3"."CASE_ID" ) ) 



SELECT
count(*)
FROM
   ( SELECT
/* ST2_CI_CASE.INOUTGRP1, EXPRESSION.OUTGRP1 */
  NVL(TRIM("ST2_CI_CASE"."CASE_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.CASE_ID: EXPRESSION */ "SRC_CASE_ID",
  "ST2_CI_CASE"."CASE_COND_FLG" "CASE_COND_FLG",
  NVL("ST2_CI_LOOKUP_VAL_L"."DESCR", 'N/A') "CASE_COND_FLG_DESCR",
  "ST2_CI_CASE"."CASE_STATUS_CD" "CASE_STATUS_CD",
  NVL("ST2_CI_CASE_STATUS_L"."STATUS_LBL", 'N/A') "CASE_STATUS_CD_DESCR",
  NVL(TRIM("ST2_CI_CASE"."CASE_TYPE_CD"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.CASE_TYPE_CD: EXPRESSION */ "CASE_TYPE_CD",
  NVL((SELECT
  "ST2_CI_CASE_TYPE_L_S"."DESCR" "DESCR"
FROM
  "ST2_CI_CASE_TYPE_L"  "ST2_CI_CASE_TYPE_L_S"
  WHERE 
  ( "ST2_CI_CASE_TYPE_L_S"."CASE_TYPE_CD" = "ST2_CI_CASE"."CASE_TYPE_CD" ) /* OPERATOR ST2_CI_CASE_TYPE_L: LOOKUP CONDITION */ AND
  ( "ST2_CI_CASE_TYPE_L_S"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT_1.OUTGRP1.FIELD_NAME */ ) /* OPERATOR ST2_CI_CASE_TYPE_L: ROW MATCH */ AND
  ( rownum = 1 ) ), 'N/A') "CASE_TYPE_CD_DESCR",
  NVL(TRIM("ST2_CI_CASE"."COMMENT_LONG"),'N/A')/* ATTRIBUTE EXPRESSION_3.OUTGRP1.COMMENT_LONG: EXPRESSION */ "COMMENT_LONG",
  NVL(TRIM((TRIM( "ST2_CI_CASE"."CONTACT_INSTR" )/* ATTRIBUTE TRIM.OUTGRP1.CONTACT_INSTR: EXPRESSION */)),'N/A')/* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_INSTR: EXPRESSION */ "CONTACT_INSTR",
  NVL(TRIM("ST2_CI_CASE"."CONTACT_METH_FLG"),'N/A')/* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_METH_FLG: EXPRESSION */ "CONTACT_METH_FLG",
  NVL("ST2_CI_LOOKUP_VAL_L_1"."DESCR", 'N/A') "CONTACT_METH_FLG_DESCR",
  NVL(TRIM("ST2_CI_CASE"."USER_ID"),1)/* ATTRIBUTE EXPRESSION_3.OUTGRP1.USER_ID: EXPRESSION */ "USER_ID",
  NVL("D_CIS_USER"."CIS_USER_KEY", 1) "USER_ID_CIS_USER_KEY",
  NVL(TRIM("ST2_CI_CASE"."PER_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.PER_ID: EXPRESSION */ "PER_ID",
  NVL(TRIM("ST2_CI_CASE"."ACCT_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.ACCT_ID: EXPRESSION */ "ACCT_ID",
  NVL(TRIM("ST2_CI_CASE"."PREM_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.PREM_ID: EXPRESSION */ "PREM_ID",
  NVL(TRIM("ST2_CI_CASE"."CONTACT_PER_ID"),1)/* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_PER_ID: EXPRESSION */ "CONTACT_PER_ID",
  TRUNC("ST2_CI_CASE_LOG"."LOG_DTTM")/* ATTRIBUTE TRUNC.OUTGRP1.LOG_DTTM: EXPRESSION */ "START_DT",
  "D_DATE_1_1"."DATE_KEY" "START_DT_CAL_KEY",
  "D_DATE_1"."DATE_KEY" "STATUS_DT_CAL_KEY",
  NVL("D_PERSON"."PERSON_KEY", 1) "PERSON_KEY",
  NVL("D_ACCOUNT"."ACCOUNT_KEY", 1) "ACCOUNT_KEY",
  NVL("D_PREMISE"."PREMISE_KEY", 1) "PREMISE_KEY",
  NVL("D_PERSON_1"."PERSON_KEY", 1) "CONTACT_PERSON_KEY",
  CASE 
  WHEN "ST2_CI_CASE"."CASE_ID" IS NULL THEN SYSDATE 
  ELSE NULL 
END/* ATTRIBUTE EXPRESSION.OUTGRP1.DELETED_DTTM: EXPRESSION */ "DELETED_DTTM",
  CASE 
  WHEN "ST2_CI_CASE"."CASE_ID" IS NULL THEN 1 
  ELSE NULL 
END/* ATTRIBUTE EXPRESSION.OUTGRP1.DELETED_FLG: EXPRESSION */ "DELETED_FLG"
FROM
    "ST2_CI_LOOKUP_VAL_L"  "ST2_CI_LOOKUP_VAL_L"   
 RIGHT OUTER JOIN   "ST2_CI_CASE"  "ST2_CI_CASE" ON ( (( "ST2_CI_LOOKUP_VAL_L"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_LOOKUP_VAL_L"."FIELD_NAME" = 'CASE_COND_FLG'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_LOOKUP_VAL_L"."FIELD_VALUE" = "ST2_CI_CASE"."CASE_COND_FLG" )) )
 LEFT OUTER JOIN   "ST2_CI_CASE_STATUS_L"  "ST2_CI_CASE_STATUS_L" ON ( (( "ST2_CI_CASE_STATUS_L"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_CASE_STATUS_L"."CASE_TYPE_CD" = "ST2_CI_CASE"."CASE_TYPE_CD" )) AND (( "ST2_CI_CASE_STATUS_L"."CASE_STATUS_CD" = "ST2_CI_CASE"."CASE_STATUS_CD" )) )
 LEFT OUTER JOIN   "ST2_CI_LOOKUP_VAL_L"  "ST2_CI_LOOKUP_VAL_L_1" ON ( (( "ST2_CI_LOOKUP_VAL_L_1"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_LOOKUP_VAL_L_1"."FIELD_VALUE" = "ST2_CI_CASE"."CONTACT_METH_FLG" )) AND (( "ST2_CI_LOOKUP_VAL_L_1"."FIELD_NAME" = 'CONTACT_METH_FLG'/* ATTRIBUTE CONSTANT_1.OUTGRP1.FIELD_NAME */ )) )
 LEFT OUTER JOIN   "D_CIS_USER"  "D_CIS_USER" ON ( ( "D_CIS_USER"."SRC_USER_ID" = "ST2_CI_CASE"."USER_ID" ) )
 LEFT OUTER JOIN   "ST2_CI_CASE_LOG"  "ST2_CI_CASE_LOG" ON ( (( "ST2_CI_CASE_LOG"."CASE_ID" = "ST2_CI_CASE"."CASE_ID" )) AND (( "ST2_CI_CASE_LOG"."CASE_LOG_TYPE_FLG" = 'CASC'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) )
 LEFT OUTER JOIN   "D_DATE"  "D_DATE_1_1" ON ( ( "D_DATE_1_1"."SRC_DATE" = (TRUNC("ST2_CI_CASE_LOG"."LOG_DTTM")/* ATTRIBUTE TRUNC.OUTGRP1.LOG_DTTM: EXPRESSION */) ) )
 LEFT OUTER JOIN   "ST2_CI_CASE_LOG"  "ST2_CI_CASE_LOG_2" ON ( (( "ST2_CI_CASE_LOG_2"."CASE_LOG_TYPE_FLG" = 'CASC'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_CASE_LOG_2"."CASE_ID" = "ST2_CI_CASE"."CASE_ID" )) )
 LEFT OUTER JOIN   "D_DATE"  "D_DATE_1" ON ( ( "D_DATE_1"."SRC_DATE" = (TRUNC("ST2_CI_CASE_LOG_2"."LOG_DTTM")/* ATTRIBUTE TRUNC_2.OUTGRP1.LOG_DTTM: EXPRESSION */) ) )
 LEFT OUTER JOIN   "D_PERSON"  "D_PERSON" ON ( ( "D_PERSON"."SRC_PER_ID" = "ST2_CI_CASE"."PER_ID" ) )
 LEFT OUTER JOIN   "D_ACCOUNT"  "D_ACCOUNT" ON ( ( "D_ACCOUNT"."SRC_ACCT_ID" = "ST2_CI_CASE"."ACCT_ID" ) )
 LEFT OUTER JOIN   "D_PREMISE"  "D_PREMISE" ON ( ( "D_PREMISE"."SRC_PREM_ID" = "ST2_CI_CASE"."PREM_ID" ) )
 LEFT OUTER JOIN   "D_PERSON"  "D_PERSON_1" ON ( ( "D_PERSON_1"."SRC_PER_ID" = "ST2_CI_CASE"."CONTACT_PER_ID" ) ) ) "C"   
 LEFT OUTER JOIN  ( SELECT
/* JOINER.OUTGRP1 */
  "ST2_CI_CASE"."CASE_ID" "SRC_CASE_ID",
  CASE 
 --  WHEN  "INGRP2"."CASE_LOG_TYPE_FLG" is null and "INGRP3"."CASE_LOG_TYPE_FLG"='CASC' 
 --  THEN (TRUNC("INGRP3"."LOG_DTTM")/* ATTRIBUTE TRUNC_2_1.OUTGRP1.LOG_DTTM_0: EXPRESSION */)
  -- WHEN  "INGRP2"."CASE_LOG_TYPE_FLG" ='STAT' and "INGRP3"."CASE_LOG_TYPE_FLG"='CASC' 
--    THEN (TRUNC("INGRP2"."LOG_DTTM")/* ATTRIBUTE TRUNC_2_1.OUTGRP1.LOG_DTTM: EXPRESSION */)
  --  ELSE  NULL
  
 
  
  
  
  
 END/* ATTRIBUTE EXPRESSION_1.OUTGRP1.STATUS_DT: EXPRESSION */ "STATUS_DT"
FROM
    "ST2_CI_CASE"  "ST2_CI_CASE"   
 LEFT OUTER JOIN  ( SELECT
/* ST2_CI_CASE_LOG_V.INOUTGRP1 */
  "ST2_CI_CASE_LOG_V"."CASE_ID" "CASE_ID",
  "ST2_CI_CASE_LOG_V"."LOG_DTTM" "LOG_DTTM",
  "ST2_CI_CASE_LOG_V"."CASE_LOG_TYPE_FLG" "CASE_LOG_TYPE_FLG"
FROM
  "ST2_CI_CASE_LOG_V"  "ST2_CI_CASE_LOG_V" ) "INGRP2" ON ( ( "ST2_CI_CASE"."CASE_ID" = "INGRP2"."CASE_ID" ) )
 LEFT OUTER JOIN  ( SELECT
/* ST2_CI_CASE_LOG_V1.INOUTGRP1 */
  "ST2_CI_CASE_LOG_V1"."CASE_ID" "CASE_ID",
  "ST2_CI_CASE_LOG_V1"."LOG_DTTM" "LOG_DTTM",
  "ST2_CI_CASE_LOG_V1"."CASE_LOG_TYPE_FLG" "CASE_LOG_TYPE_FLG"
FROM
  "ST2_CI_CASE_LOG_V1"  "ST2_CI_CASE_LOG_V1" ) "INGRP3" ON ( ( "ST2_CI_CASE"."CASE_ID" = "INGRP3"."CASE_ID" ) ) ) "D" ON ( ( "C"."SRC_CASE_ID" = "D"."SRC_CASE_ID" ) )
  where "STATUS_DT" is not null
-- )
  --  "MERGE_SUBQUERY"
--ON (
--  "D_CASE_3"."SRC_CASE_ID" = "MERGE_SUBQUERY"."SRC_CASE_ID"
--  )



SELECT
count(*)
FROM
   ( SELECT
/* ST2_CI_CASE.INOUTGRP1, EXPRESSION.OUTGRP1 */
  NVL(TRIM("ST2_CI_CASE"."CASE_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.CASE_ID: EXPRESSION */ "SRC_CASE_ID",
  "ST2_CI_CASE"."CASE_COND_FLG" "CASE_COND_FLG",
  NVL("ST2_CI_LOOKUP_VAL_L"."DESCR", 'N/A') "CASE_COND_FLG_DESCR",
  "ST2_CI_CASE"."CASE_STATUS_CD" "CASE_STATUS_CD",
  NVL("ST2_CI_CASE_STATUS_L"."STATUS_LBL", 'N/A') "CASE_STATUS_CD_DESCR",
  NVL(TRIM("ST2_CI_CASE"."CASE_TYPE_CD"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.CASE_TYPE_CD: EXPRESSION */ "CASE_TYPE_CD",
  NVL((SELECT
  "ST2_CI_CASE_TYPE_L_S"."DESCR" "DESCR"
FROM
  "ST2_CI_CASE_TYPE_L"  "ST2_CI_CASE_TYPE_L_S"
  WHERE 
  ( "ST2_CI_CASE_TYPE_L_S"."CASE_TYPE_CD" = "ST2_CI_CASE"."CASE_TYPE_CD" ) /* OPERATOR ST2_CI_CASE_TYPE_L: LOOKUP CONDITION */ AND
  ( "ST2_CI_CASE_TYPE_L_S"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT_1.OUTGRP1.FIELD_NAME */ ) /* OPERATOR ST2_CI_CASE_TYPE_L: ROW MATCH */ AND
  ( rownum = 1 ) ), 'N/A') "CASE_TYPE_CD_DESCR",
  NVL(TRIM("ST2_CI_CASE"."COMMENT_LONG"),'N/A')/* ATTRIBUTE EXPRESSION_3.OUTGRP1.COMMENT_LONG: EXPRESSION */ "COMMENT_LONG",
  NVL(TRIM((TRIM( "ST2_CI_CASE"."CONTACT_INSTR" )/* ATTRIBUTE TRIM.OUTGRP1.CONTACT_INSTR: EXPRESSION */)),'N/A')/* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_INSTR: EXPRESSION */ "CONTACT_INSTR",
  NVL(TRIM("ST2_CI_CASE"."CONTACT_METH_FLG"),'N/A')/* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_METH_FLG: EXPRESSION */ "CONTACT_METH_FLG",
  NVL("ST2_CI_LOOKUP_VAL_L_1"."DESCR", 'N/A') "CONTACT_METH_FLG_DESCR",
  NVL(TRIM("ST2_CI_CASE"."USER_ID"),1)/* ATTRIBUTE EXPRESSION_3.OUTGRP1.USER_ID: EXPRESSION */ "USER_ID",
  NVL("D_CIS_USER"."CIS_USER_KEY", 1) "USER_ID_CIS_USER_KEY",
  NVL(TRIM("ST2_CI_CASE"."PER_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.PER_ID: EXPRESSION */ "PER_ID",
  NVL(TRIM("ST2_CI_CASE"."ACCT_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.ACCT_ID: EXPRESSION */ "ACCT_ID",
  NVL(TRIM("ST2_CI_CASE"."PREM_ID"),'N/A')/* ATTRIBUTE EXPRESSION.OUTGRP1.PREM_ID: EXPRESSION */ "PREM_ID",
  NVL(TRIM("ST2_CI_CASE"."CONTACT_PER_ID"),1)/* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_PER_ID: EXPRESSION */ "CONTACT_PER_ID",
  TRUNC("ST2_CI_CASE_LOG"."LOG_DTTM")/* ATTRIBUTE TRUNC.OUTGRP1.LOG_DTTM: EXPRESSION */ "START_DT",
  "D_DATE_1_1"."DATE_KEY" "START_DT_CAL_KEY",
  "D_DATE_1"."DATE_KEY" "STATUS_DT_CAL_KEY",
  NVL("D_PERSON"."PERSON_KEY", 1) "PERSON_KEY",
  NVL("D_ACCOUNT"."ACCOUNT_KEY", 1) "ACCOUNT_KEY",
  NVL("D_PREMISE"."PREMISE_KEY", 1) "PREMISE_KEY",
  NVL("D_PERSON_1"."PERSON_KEY", 1) "CONTACT_PERSON_KEY",
  CASE 
  WHEN "ST2_CI_CASE"."CASE_ID" IS NULL THEN SYSDATE 
  ELSE NULL 
END/* ATTRIBUTE EXPRESSION.OUTGRP1.DELETED_DTTM: EXPRESSION */ "DELETED_DTTM",
  CASE 
  WHEN "ST2_CI_CASE"."CASE_ID" IS NULL THEN 1 
  ELSE NULL 
END/* ATTRIBUTE EXPRESSION.OUTGRP1.DELETED_FLG: EXPRESSION */ "DELETED_FLG"
FROM
    "ST2_CI_LOOKUP_VAL_L"  "ST2_CI_LOOKUP_VAL_L"   
 RIGHT OUTER JOIN   "ST2_CI_CASE"  "ST2_CI_CASE" ON ( (( "ST2_CI_LOOKUP_VAL_L"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_LOOKUP_VAL_L"."FIELD_NAME" = 'CASE_COND_FLG'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_LOOKUP_VAL_L"."FIELD_VALUE" = "ST2_CI_CASE"."CASE_COND_FLG" )) )
 LEFT OUTER JOIN   "ST2_CI_CASE_STATUS_L"  "ST2_CI_CASE_STATUS_L" ON ( (( "ST2_CI_CASE_STATUS_L"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_CASE_STATUS_L"."CASE_TYPE_CD" = "ST2_CI_CASE"."CASE_TYPE_CD" )) AND (( "ST2_CI_CASE_STATUS_L"."CASE_STATUS_CD" = "ST2_CI_CASE"."CASE_STATUS_CD" )) )
 LEFT OUTER JOIN   "ST2_CI_LOOKUP_VAL_L"  "ST2_CI_LOOKUP_VAL_L_1" ON ( (( "ST2_CI_LOOKUP_VAL_L_1"."LANGUAGE_CD" = 'EST'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_LOOKUP_VAL_L_1"."FIELD_VALUE" = "ST2_CI_CASE"."CONTACT_METH_FLG" )) AND (( "ST2_CI_LOOKUP_VAL_L_1"."FIELD_NAME" = 'CONTACT_METH_FLG'/* ATTRIBUTE CONSTANT_1.OUTGRP1.FIELD_NAME */ )) )
 LEFT OUTER JOIN   "D_CIS_USER"  "D_CIS_USER" ON ( ( "D_CIS_USER"."SRC_USER_ID" = "ST2_CI_CASE"."USER_ID" ) )
 LEFT OUTER JOIN   "ST2_CI_CASE_LOG"  "ST2_CI_CASE_LOG" ON ( (( "ST2_CI_CASE_LOG"."CASE_ID" = "ST2_CI_CASE"."CASE_ID" )) AND (( "ST2_CI_CASE_LOG"."CASE_LOG_TYPE_FLG" = 'CASC'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) )
 LEFT OUTER JOIN   "D_DATE"  "D_DATE_1_1" ON ( ( "D_DATE_1_1"."SRC_DATE" = (TRUNC("ST2_CI_CASE_LOG"."LOG_DTTM")/* ATTRIBUTE TRUNC.OUTGRP1.LOG_DTTM: EXPRESSION */) ) )
 LEFT OUTER JOIN   "ST2_CI_CASE_LOG"  "ST2_CI_CASE_LOG_2" ON ( (( "ST2_CI_CASE_LOG_2"."CASE_LOG_TYPE_FLG" = 'CASC'/* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */ )) AND (( "ST2_CI_CASE_LOG_2"."CASE_ID" = "ST2_CI_CASE"."CASE_ID" )) )
 LEFT OUTER JOIN   "D_DATE"  "D_DATE_1" ON ( ( "D_DATE_1"."SRC_DATE" = (TRUNC("ST2_CI_CASE_LOG_2"."LOG_DTTM")/* ATTRIBUTE TRUNC_2.OUTGRP1.LOG_DTTM: EXPRESSION */) ) )
 LEFT OUTER JOIN   "D_PERSON"  "D_PERSON" ON ( ( "D_PERSON"."SRC_PER_ID" = "ST2_CI_CASE"."PER_ID" ) )
 LEFT OUTER JOIN   "D_ACCOUNT"  "D_ACCOUNT" ON ( ( "D_ACCOUNT"."SRC_ACCT_ID" = "ST2_CI_CASE"."ACCT_ID" ) )
 LEFT OUTER JOIN   "D_PREMISE"  "D_PREMISE" ON ( ( "D_PREMISE"."SRC_PREM_ID" = "ST2_CI_CASE"."PREM_ID" ) )
 LEFT OUTER JOIN   "D_PERSON"  "D_PERSON_1" ON ( ( "D_PERSON_1"."SRC_PER_ID" = "ST2_CI_CASE"."CONTACT_PER_ID" ) ) ) "C"   



SELECT
/* JOINER.OUTGRP1 */
  "ST2_CI_CASE"."CASE_ID" "SRC_CASE_ID",
  CASE 
   WHEN  "INGRP2"."CASE_LOG_TYPE_FLG" is null and "INGRP3"."CASE_LOG_TYPE_FLG"='CASC' 
   THEN (TRUNC("INGRP3"."LOG_DTTM")/* ATTRIBUTE TRUNC_2_1.OUTGRP1.LOG_DTTM_0: EXPRESSION */)
   WHEN  "INGRP2"."CASE_LOG_TYPE_FLG" ='STAT' and "INGRP3"."CASE_LOG_TYPE_FLG"='CASC' 
    THEN (TRUNC("INGRP2"."LOG_DTTM")/* ATTRIBUTE TRUNC_2_1.OUTGRP1.LOG_DTTM: EXPRESSION */)
    ELSE  NULL
 END/* ATTRIBUTE EXPRESSION_1.OUTGRP1.STATUS_DT: EXPRESSION */ "STATUS_DT"
FROM
    "ST2_CI_CASE"  "ST2_CI_CASE"   
 LEFT OUTER JOIN  ( SELECT
/* ST2_CI_CASE_LOG_V.INOUTGRP1 */
  "ST2_CI_CASE_LOG_V"."CASE_ID" "CASE_ID",
  "ST2_CI_CASE_LOG_V"."LOG_DTTM" "LOG_DTTM",
  "ST2_CI_CASE_LOG_V"."CASE_LOG_TYPE_FLG" "CASE_LOG_TYPE_FLG"
FROM
  "ST2_CI_CASE_LOG_V"  "ST2_CI_CASE_LOG_V" ) "INGRP2" ON ( ( "ST2_CI_CASE"."CASE_ID" = "INGRP2"."CASE_ID" ) )
 LEFT OUTER JOIN  ( SELECT
/* ST2_CI_CASE_LOG_V1.INOUTGRP1 */
  "ST2_CI_CASE_LOG_V1"."CASE_ID" "CASE_ID",
  "ST2_CI_CASE_LOG_V1"."LOG_DTTM" "LOG_DTTM",
  "ST2_CI_CASE_LOG_V1"."CASE_LOG_TYPE_FLG" "CASE_LOG_TYPE_FLG"
FROM
  "ST2_CI_CASE_LOG_V1"  "ST2_CI_CASE_LOG_V1" ) "INGRP3" ON ( ( "ST2_CI_CASE"."CASE_ID" = "INGRP3"."CASE_ID" ) )





SELECT /* C_SYSDATE.OUTGRP1 */
       NULL "MERGE_COL_ALIAS",
       SYSDATE                     /* ATTRIBUTE C_SYSDATE.OUTGRP1.C_SYSDATE */
              "C_SYSDATE",
       "C"."SRC_CASE_ID" "SRC_CASE_ID",
       "C"."CASE_COND_FLG" "CASE_COND_FLG",
       "C"."CASE_COND_FLG_DESCR" "CASE_COND_FLG_DESCR",
       "C"."CASE_STATUS_CD" "CASE_STATUS_CD",
       "C"."CASE_STATUS_CD_DESCR" "CASE_STATUS_CD_DESCR",
       "C"."CASE_TYPE_CD" "CASE_TYPE_CD",
       "C"."CASE_TYPE_CD_DESCR" "CASE_TYPE_CD_DESCR",
       "C"."COMMENT_LONG" "COMMENT_LONG",
       "C"."CONTACT_INSTR" "CONTACT_INSTR",
       "C"."CONTACT_METH_FLG" "CONTACT_METH_FLG",
       "C"."CONTACT_METH_FLG_DESCR" "CONTACT_METH_FLG_DESCR",
       "C"."USER_ID" "USER_ID",
       "C"."USER_ID_CIS_USER_KEY" "USER_ID_CIS_USER_KEY",
       "C"."PER_ID" "PER_ID",
       "C"."ACCT_ID" "ACCT_ID",
       "C"."PREM_ID" "PREM_ID",
       "C"."CONTACT_PER_ID" "CONTACT_PER_ID",
       "C"."START_DT" "START_DT",
       "C"."START_DT_CAL_KEY" "START_DT_CAL_KEY",
       "D"."STATUS_DT" "STATUS_DT_0",
       "C"."STATUS_DT_CAL_KEY" "STATUS_DT_CAL_KEY",
       "C"."PERSON_KEY" "PERSON_KEY",
       "C"."ACCOUNT_KEY" "ACCOUNT_KEY",
       "C"."PREMISE_KEY" "PREMISE_KEY",
       "C"."CONTACT_PERSON_KEY" "CONTACT_PERSON_KEY",
       "C"."DELETED_DTTM" "DELETED_DTTM",
       "C"."DELETED_FLG" "DELETED_FLG"
  FROM    (SELECT /* ST2_CI_CASE.INOUTGRP1, EXPRESSION.OUTGRP1 */
                  NVL (TRIM ("ST2_CI_CASE"."CASE_ID"), 'N/A') /* ATTRIBUTE EXPRESSION.OUTGRP1.CASE_ID: EXPRESSION */
                     "SRC_CASE_ID",
                  "ST2_CI_CASE"."CASE_COND_FLG" "CASE_COND_FLG",
                  NVL ("ST2_CI_LOOKUP_VAL_L"."DESCR", 'N/A')
                     "CASE_COND_FLG_DESCR",
                  "ST2_CI_CASE"."CASE_STATUS_CD" "CASE_STATUS_CD",
                  NVL ("ST2_CI_CASE_STATUS_L"."STATUS_LBL", 'N/A')
                     "CASE_STATUS_CD_DESCR",
                  NVL (TRIM ("ST2_CI_CASE"."CASE_TYPE_CD"), 'N/A') /* ATTRIBUTE EXPRESSION.OUTGRP1.CASE_TYPE_CD: EXPRESSION */
                     "CASE_TYPE_CD",
                  NVL (
                     (SELECT "ST2_CI_CASE_TYPE_L_S"."DESCR" "DESCR"
                        FROM "ST2_CI_CASE_TYPE_L" "ST2_CI_CASE_TYPE_L_S"
                       WHERE ("ST2_CI_CASE_TYPE_L_S"."CASE_TYPE_CD" =
                                 "ST2_CI_CASE"."CASE_TYPE_CD") /* OPERATOR ST2_CI_CASE_TYPE_L: LOOKUP CONDITION */
                             AND ("ST2_CI_CASE_TYPE_L_S"."LANGUAGE_CD" =
                                     'EST' /* ATTRIBUTE CONSTANT_1.OUTGRP1.FIELD_NAME */
                                          ) /* OPERATOR ST2_CI_CASE_TYPE_L: ROW MATCH */
                             AND (ROWNUM =
                                     1)),
                     'N/A')
                     "CASE_TYPE_CD_DESCR",
                  NVL (TRIM ("ST2_CI_CASE"."COMMENT_LONG"), 'N/A') /* ATTRIBUTE EXPRESSION_3.OUTGRP1.COMMENT_LONG: EXPRESSION */
                     "COMMENT_LONG",
                  NVL (
                     TRIM (
                        (TRIM ("ST2_CI_CASE"."CONTACT_INSTR") /* ATTRIBUTE TRIM.OUTGRP1.CONTACT_INSTR: EXPRESSION */
                                                             )),
                     'N/A') /* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_INSTR: EXPRESSION */
                     "CONTACT_INSTR",
                  NVL (TRIM ("ST2_CI_CASE"."CONTACT_METH_FLG"), 'N/A') /* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_METH_FLG: EXPRESSION */
                     "CONTACT_METH_FLG",
                  NVL ("ST2_CI_LOOKUP_VAL_L_1"."DESCR", 'N/A')
                     "CONTACT_METH_FLG_DESCR",
                  NVL (TRIM ("ST2_CI_CASE"."USER_ID"), 1) /* ATTRIBUTE EXPRESSION_3.OUTGRP1.USER_ID: EXPRESSION */
                     "USER_ID",
                  NVL ("D_CIS_USER"."CIS_USER_KEY", 1) "USER_ID_CIS_USER_KEY",
                  NVL (TRIM ("ST2_CI_CASE"."PER_ID"), 'N/A') /* ATTRIBUTE EXPRESSION.OUTGRP1.PER_ID: EXPRESSION */
                     "PER_ID",
                  NVL (TRIM ("ST2_CI_CASE"."ACCT_ID"), 'N/A') /* ATTRIBUTE EXPRESSION.OUTGRP1.ACCT_ID: EXPRESSION */
                     "ACCT_ID",
                  NVL (TRIM ("ST2_CI_CASE"."PREM_ID"), 'N/A') /* ATTRIBUTE EXPRESSION.OUTGRP1.PREM_ID: EXPRESSION */
                     "PREM_ID",
                  NVL (TRIM ("ST2_CI_CASE"."CONTACT_PER_ID"), 1) /* ATTRIBUTE EXPRESSION_3.OUTGRP1.CONTACT_PER_ID: EXPRESSION */
                     "CONTACT_PER_ID",
                  TRUNC ("ST2_CI_CASE_LOG"."LOG_DTTM") /* ATTRIBUTE TRUNC.OUTGRP1.LOG_DTTM: EXPRESSION */
                     "START_DT",
                  "D_DATE_1_1"."DATE_KEY" "START_DT_CAL_KEY",
                  "D_DATE_1"."DATE_KEY" "STATUS_DT_CAL_KEY",
                  NVL ("D_PERSON"."PERSON_KEY", 1) "PERSON_KEY",
                  NVL ("D_ACCOUNT"."ACCOUNT_KEY", 1) "ACCOUNT_KEY",
                  NVL ("D_PREMISE"."PREMISE_KEY", 1) "PREMISE_KEY",
                  NVL ("D_PERSON_1"."PERSON_KEY", 1) "CONTACT_PERSON_KEY",
                  CASE
                     WHEN "ST2_CI_CASE"."CASE_ID" IS NULL THEN SYSDATE
                     ELSE NULL
                  END /* ATTRIBUTE EXPRESSION.OUTGRP1.DELETED_DTTM: EXPRESSION */
                     "DELETED_DTTM",
                  CASE
                     WHEN "ST2_CI_CASE"."CASE_ID" IS NULL THEN 1
                     ELSE NULL
                  END /* ATTRIBUTE EXPRESSION.OUTGRP1.DELETED_FLG: EXPRESSION */
                     "DELETED_FLG"
             FROM "ST2_CI_LOOKUP_VAL_L" "ST2_CI_LOOKUP_VAL_L"
                  RIGHT OUTER JOIN "ST2_CI_CASE" "ST2_CI_CASE"
                     ON ( ( ("ST2_CI_LOOKUP_VAL_L"."LANGUAGE_CD" = 'EST' /* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */
                                                                        ))
                         AND ( ("ST2_CI_LOOKUP_VAL_L"."FIELD_NAME" =
                                   'CASE_COND_FLG' /* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */
                                                  ))
                         AND ( ("ST2_CI_LOOKUP_VAL_L"."FIELD_VALUE" =
                                   "ST2_CI_CASE"."CASE_COND_FLG")))
                  LEFT OUTER JOIN "ST2_CI_CASE_STATUS_L" "ST2_CI_CASE_STATUS_L"
                     ON ( ( ("ST2_CI_CASE_STATUS_L"."LANGUAGE_CD" = 'EST' /* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */
                                                                         ))
                         AND ( ("ST2_CI_CASE_STATUS_L"."CASE_TYPE_CD" =
                                   "ST2_CI_CASE"."CASE_TYPE_CD"))
                         AND ( ("ST2_CI_CASE_STATUS_L"."CASE_STATUS_CD" =
                                   "ST2_CI_CASE"."CASE_STATUS_CD")))
                  LEFT OUTER JOIN "ST2_CI_LOOKUP_VAL_L" "ST2_CI_LOOKUP_VAL_L_1"
                     ON ( ( ("ST2_CI_LOOKUP_VAL_L_1"."LANGUAGE_CD" = 'EST' /* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */
                                                                          ))
                         AND ( ("ST2_CI_LOOKUP_VAL_L_1"."FIELD_VALUE" =
                                   "ST2_CI_CASE"."CONTACT_METH_FLG"))
                         AND ( ("ST2_CI_LOOKUP_VAL_L_1"."FIELD_NAME" =
                                   'CONTACT_METH_FLG' /* ATTRIBUTE CONSTANT_1.OUTGRP1.FIELD_NAME */
                                                     )))
                  LEFT OUTER JOIN "D_CIS_USER" "D_CIS_USER"
                     ON ( ("D_CIS_USER"."SRC_USER_ID" =
                              "ST2_CI_CASE"."USER_ID"))
                  LEFT OUTER JOIN "ST2_CI_CASE_LOG" "ST2_CI_CASE_LOG"
                     ON ( ( ("ST2_CI_CASE_LOG"."CASE_ID" =
                                "ST2_CI_CASE"."CASE_ID"))
                         AND ( ("ST2_CI_CASE_LOG"."CASE_LOG_TYPE_FLG" =
                                   'CASC' /* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */
                                         )))
                  LEFT OUTER JOIN "D_DATE" "D_DATE_1_1"
                     ON ( ("D_DATE_1_1"."SRC_DATE" =
                              (TRUNC ("ST2_CI_CASE_LOG"."LOG_DTTM") /* ATTRIBUTE TRUNC.OUTGRP1.LOG_DTTM: EXPRESSION */
                                                                   )))
                  LEFT OUTER JOIN "ST2_CI_CASE_LOG" "ST2_CI_CASE_LOG_2"
                     ON ( ( ("ST2_CI_CASE_LOG_2"."CASE_LOG_TYPE_FLG" = 'CASC' /* ATTRIBUTE CONSTANT.OUTGRP1.CASE_LOG_TYPE_FLG */
                                                                             ))
                         AND ( ("ST2_CI_CASE_LOG_2"."CASE_ID" =
                                   "ST2_CI_CASE"."CASE_ID")))
                  LEFT OUTER JOIN "D_DATE" "D_DATE_1"
                     ON ( ("D_DATE_1"."SRC_DATE" =
                              (TRUNC ("ST2_CI_CASE_LOG_2"."LOG_DTTM") /* ATTRIBUTE TRUNC_2.OUTGRP1.LOG_DTTM: EXPRESSION */
                                                                     )))
                  LEFT OUTER JOIN "D_PERSON" "D_PERSON"
                     ON ( ("D_PERSON"."SRC_PER_ID" = "ST2_CI_CASE"."PER_ID"))
                  LEFT OUTER JOIN "D_ACCOUNT" "D_ACCOUNT"
                     ON ( ("D_ACCOUNT"."SRC_ACCT_ID" =
                              "ST2_CI_CASE"."ACCT_ID"))
                  LEFT OUTER JOIN "D_PREMISE" "D_PREMISE"
                     ON ( ("D_PREMISE"."SRC_PREM_ID" =
                              "ST2_CI_CASE"."PREM_ID"))
                  LEFT OUTER JOIN "D_PERSON" "D_PERSON_1"
                     ON ( ("D_PERSON_1"."SRC_PER_ID" =
                              "ST2_CI_CASE"."CONTACT_PER_ID"))) "C"
       LEFT OUTER JOIN
          (SELECT /* JOINER.OUTGRP1 */
                  "ST2_CI_CASE"."CASE_ID" "SRC_CASE_ID",
                  CASE
                     WHEN "INGRP2"."CASE_LOG_TYPE_FLG" IS NULL
                          AND "INGRP3"."CASE_LOG_TYPE_FLG" = 'CASC'
                     THEN
                        (TRUNC ("INGRP3"."LOG_DTTM") /* ATTRIBUTE TRUNC_2_1.OUTGRP1.LOG_DTTM_0: EXPRESSION */
                                                    )
                     WHEN "INGRP2"."CASE_LOG_TYPE_FLG" = 'STAT'
                          AND "INGRP3"."CASE_LOG_TYPE_FLG" = 'CASC'
                     THEN
                        (TRUNC ("INGRP2"."LOG_DTTM") /* ATTRIBUTE TRUNC_2_1.OUTGRP1.LOG_DTTM: EXPRESSION */
                                                    )
                     ELSE
                        NULL
                  END /* ATTRIBUTE EXPRESSION_1.OUTGRP1.STATUS_DT: EXPRESSION */
                     "STATUS_DT"
             FROM "ST2_CI_CASE" "ST2_CI_CASE"
                  LEFT OUTER JOIN (SELECT /* ST2_CI_CASE_LOG_V.INOUTGRP1 */
                                          "ST2_CI_CASE_LOG_V"."CASE_ID"
                                             "CASE_ID",
                                          "ST2_CI_CASE_LOG_V"."LOG_DTTM"
                                             "LOG_DTTM",
                                          "ST2_CI_CASE_LOG_V"."CASE_LOG_TYPE_FLG"
                                             "CASE_LOG_TYPE_FLG"
                                     FROM "ST2_CI_CASE_LOG_V" "ST2_CI_CASE_LOG_V") "INGRP2"
                     ON ( ("ST2_CI_CASE"."CASE_ID" = "INGRP2"."CASE_ID"))
                  LEFT OUTER JOIN (SELECT /* ST2_CI_CASE_LOG_V1.INOUTGRP1 */
                                          "ST2_CI_CASE_LOG_V1"."CASE_ID"
                                             "CASE_ID",
                                          "ST2_CI_CASE_LOG_V1"."LOG_DTTM"
                                             "LOG_DTTM",
                                          "ST2_CI_CASE_LOG_V1"."CASE_LOG_TYPE_FLG"
                                             "CASE_LOG_TYPE_FLG"
                                     FROM "ST2_CI_CASE_LOG_V1" "ST2_CI_CASE_LOG_V1") "INGRP3"
                     ON ( ("ST2_CI_CASE"."CASE_ID" = "INGRP3"."CASE_ID"))) "D"
      ON ( ("C"."SRC_CASE_ID" =trunc( "D"."SRC_CASE_ID")))
     -- order by  "C"."SRC_CASE_ID"
WHERE  "D"."STATUS_DT" is not null--"C"."SRC_CASE_ID" = '70240'
-- )
--  "MERGE_SUBQUERY"is n
--ON (
--  "D_CASE_3"."SRC_CASE_ID" = "MERGE_SUBQUERY"."SRC_CASE_ID"
-- )



 SELECT  "ST2_CI_CASE"."CASE_ID",
           MAX (st2_CI_CASE_LOG.log_dttm) log_dttm--,
   --      st2_CI_CASE_LOG.log_dttm,
    --        st2_CI_CASE_LOG.CASE_LOG_TYPE_FLG
       FROM    "ST2_CI_CASE" "ST2_CI_CASE",ST2_CI_CASE_LOG
       where "ST2_CI_CASE"."CASE_ID" = "ST2_CI_CASE_LOG"."CASE_ID"(+)
       and ST2_CI_CASE."CASE_STATUS_CD" =  ST2_CI_CASE_LOG. CASE_STATUS_CD 
       AND (  st2_CI_CASE_LOG.CASE_LOG_TYPE_FLG = 'STAT')
       group by  "ST2_CI_CASE"."CASE_ID",
           log_dttm
       having count( "ST2_CI_CASE"."CASE_ID") > 1;


























